FROM  maven:3.8.7-openjdk-18 AS build
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package

##runtime stage
FROM amazoncorretto:17
#dfine things

WORKDIR /app
#de la carpeta build copiaremos el jar
COPY --from=build /build/target/crud-repaso-*.jar /app/

EXPOSE 8088

cmd java -jar crud-repaso-1.0.0.jar
